//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCSD.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.MappingFileUsers = new HashSet<MappingFileUser>();
            this.MappingUserGroups = new HashSet<MappingUserGroup>();
            this.MappingUserTypes = new HashSet<MappingUserType>();
            this.UserAuthentications = new HashSet<UserAuthentication>();
        }
    
        public string UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string DOB { get; set; }
        public string Marital { get; set; }
        public string CreatedAt { get; set; }
        public string ModifiedAt { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<MappingFileUser> MappingFileUsers { get; set; }
        public virtual ICollection<MappingUserGroup> MappingUserGroups { get; set; }
        public virtual ICollection<MappingUserType> MappingUserTypes { get; set; }
        public virtual ICollection<UserAuthentication> UserAuthentications { get; set; }
    }
}
