//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCSD.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileBanar
    {
        public FileBanar()
        {
            this.MappingFileBanars = new HashSet<MappingFileBanar>();
        }
    
        public int Id { get; set; }
        public byte[] Banar { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<MappingFileBanar> MappingFileBanars { get; set; }
    }
}
