//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCSD.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileKey
    {
        public FileKey()
        {
            this.MappingFileKeys = new HashSet<MappingFileKey>();
        }
    
        public int Id { get; set; }
        public string SYMKey { get; set; }
        public byte[] ASYMKey { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<MappingFileKey> MappingFileKeys { get; set; }
    }
}
