//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCSD.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MappingUserType
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int UserTypeId { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
