//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCSD.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCSDEntities1 : DbContext
    {
        public SCSDEntities1()
            : base("name=SCSDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FileBanar> FileBanars { get; set; }
        public DbSet<FileContent> FileContents { get; set; }
        public DbSet<FileKey> FileKeys { get; set; }
        public DbSet<FileMetadata> FileMetadatas { get; set; }
        public DbSet<MappingFileBanar> MappingFileBanars { get; set; }
        public DbSet<MappingFileCheckSum> MappingFileCheckSums { get; set; }
        public DbSet<MappingFileContent> MappingFileContents { get; set; }
        public DbSet<MappingFileKey> MappingFileKeys { get; set; }
        public DbSet<MappingFileUser> MappingFileUsers { get; set; }
        public DbSet<MappingUserGroup> MappingUserGroups { get; set; }
        public DbSet<MappingUser> MappingUsers { get; set; }
        public DbSet<MappingUserType> MappingUserTypes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserAuthentication> UserAuthentications { get; set; }
        public DbSet<UserGroupType> UserGroupTypes { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
    }
}
